use_frameworks!

platform :ios, '10.0'

target 'ZoeFoundation_Example' do
  pod 'ZoeFoundation', :path => '../'

  target 'ZoeFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
